title: Tomi Falode # your name (or website title) here
logo: "/Tomi.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst 
  <br><br>
  SQL|POWERBI|PYTHON
  <br><br>
  Maintenance Planner
  <a href="https://www.linkedin.com/in/falode-tomisin-m-eng-14098ba7/">View My LinkedIn Profile</a> 
  <a href="https://twitter.com/Tomifalode">View My Twitter Profile</a> 
    theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
